# Generated by Django 4.0.5 on 2022-06-18 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_pbi_articles'),
    ]

    operations = [
        migrations.CreateModel(
            name='Last_Refreshh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateTime', models.DateTimeField()),
                ('Nickname', models.CharField(max_length=100)),
            ],
        ),
    ]
