# Generated by Django 4.0.5 on 2022-07-09 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_last_refreshh'),
    ]

    operations = [
        migrations.CreateModel(
            name='Google_trends',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateTime', models.DateField()),
                ('PowerBi_trend', models.IntegerField()),
                ('Tableau_trend', models.IntegerField()),
                ('Qlik_trend', models.IntegerField()),
            ],
        ),
    ]
