# Generated by Django 4.0.5 on 2022-07-09 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_google_trends'),
    ]

    operations = [
        migrations.CreateModel(
            name='Refresh_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateTime', models.DateTimeField(auto_now=True)),
                ('Nickname', models.CharField(max_length=200)),
            ],
        ),
    ]
